// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/work.tsx";
import * as $5 from "./routes/work/[slug].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Gradient/Gradient.tsx";
import * as $$2 from "./islands/Gradient/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/work.tsx": $4,
    "./routes/work/[slug].tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Gradient/Gradient.tsx": $$1,
    "./islands/Gradient/index.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
